version: '3'
services:
  # ##################
  # Traefik
  # ##################
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8001:8001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

  tmapi:
    build: ./nginx
    environment:
      APP_HOST_NAME: 'task-management-api'
      APP_HOST_PORT: 8001
    container_name: tmapi_nginx
    restart: always
    depends_on:
      - task-management-api
    labels:
      - "traefik.backend=tmapi"
      - "traefik.frontend.rule=Host:tmapi.docker.localhost"
      - "traefik.port=9000"
      - "traefik.enable=true"

  # ##################
  # Task management System Application
  # ##################
  task-management-api:
    build:
      context: ./task-management-api
      dockerfile: local.Dockerfile
    environment:
      APP_NAME: 'TaskManagementAPI'
      FLASK_CONFIG: 'development'
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: task_management
      DB_USER: root
      DB_PASSWORD: example
      DOMAIN: 'tmapi.docker.localhost'
      DEBUG_MODE: 'True'
      CELERY_BROKER_URL: 'amqp://rabbitmq:rabbitmq@rabbit1:5672/'
      CELERY_RESULT_BACKEND: 'rpc://'
    volumes:
      - ./task-management-api:/app
    expose:
      - 8001
    depends_on:
      - mysql
      - rabbit1
    labels:
      - "traefik.backend=task-management-api"
      - "traefik.frontend.rule=Host:task-management-api.docker.localhost"
      - "traefik.port=8001"
      - "traefik.enable=true"

  # ##################
  # Mysql Database
  # ##################
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_database:/var/lib/mysql
      - ./mysql_dumps:/dumps
    environment:
      MYSQL_ROOT_PASSWORD: example


  # ##################
  # phpMyAdmin
  # ##################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    labels:
      - "traefik.backend=phpmyadmin"
      - "traefik.frontend.rule=Host:phpmyadmin.docker.localhost"
      - "traefik.port=80"
      - "traefik.enable=true"
    depends_on:
      - mysql

  # ##################
  # CRON dumps mysql
  # ##################
  mysql_dump:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      CRON_TIME: "* * * * *" # every minute
    volumes:
      - ./mysql_dumps:/backup
    depends_on:
      - mysql

  # ##################
  # Rabbit MQ server
  # ##################
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
#    ports:
#      - "15672:15672"
#      - "5672:5672"
    labels:
      - "traefik.backend=rabbit"
      - "traefik.frontend.rule=Host:rabbit.docker.localhost"
      - "traefik.port=15672"
      - "traefik.enable=true"
    volumes:
      - "./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"

  # ##################
  # Redis server
  # ##################
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    labels:
      - "traefik.backend=redis"
      - "traefik.frontend.rule=Host:redis.docker.localhost"
      - "traefik.port=6379"
      - "traefik.enable=true"

volumes:
  mysql_database:
